{% set version = "0.4-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mitml
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mitml_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mitml/mitml_{{ version }}.tar.gz
  sha256: ec10c29bc58a9ca6bda666db6d24bf54910b89fe72d901b9da7edc6ea81389af

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-haven
    - r-jomo
    - r-pan
  run:
    - r-base
    - r-haven
    - r-jomo
    - r-pan

test:
  commands:
    - $R -e "library('mitml')"           # [not win]
    - "\"%R%\" -e \"library('mitml')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mitml
  license: GPL (>= 2)
  summary: Provides tools for multiple imputation of missing data in multilevel modeling. Includes a user-friendly interface to the packages 'pan' and 'jomo', and several functions for visualization, data management and the analysis  of multiply imputed data sets.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: mitml
# Type: Package
# Title: Tools for Multiple Imputation in Multilevel Modeling
# Version: 0.3-7
# Date: 2019-01-02
# Author: Simon Grund [aut,cre], Alexander Robitzsch [aut], Oliver Luedtke [aut]
# Maintainer: Simon Grund <grund@ipn.uni-kiel.de>
# BugReports: https://github.com/simongrund1/mitml/issues
# Imports: pan, jomo, haven, grDevices, graphics, stats, utils
# Suggests: mice, miceadds, Amelia, lme4, nlme, geepack, survival, knitr, rmarkdown
# LazyData: true
# LazyLoad: true
# Description: Provides tools for multiple imputation of missing data in multilevel modeling. Includes a user-friendly interface to the packages 'pan' and 'jomo', and several functions for visualization, data management and the analysis  of multiply imputed data sets.
# License: GPL (>= 2)
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-01-02 10:26:03 UTC; simon
# Repository: CRAN
# Date/Publication: 2019-01-07 18:10:03 UTC
