appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: XdMzj5BfG3/NpHJ1aBGs81JhqX8xxJQ/GWlZWhXiFHeCXrAFrVRsr6fYpZb/+TQBg3ubtKSz2lgwo8HwM9vujNZGhRO9P+oHGBSWBi2iMXjoL0rDJiCVNM5g7kV7Nb3drUOi493zI0mNlOd6nzRV1t5ZPp7zkASdqKhnuPIeW8yu1ttgU9SN0bH1+fOVBIADHjJ/Xm87+7lTAOh/3qZlijJ0VsxreKYyUwCtHFmHQD0EOa2lG1dGuChp6YZ9padbJtgnxaK/ZpkBh+4O2R41b4PrxX0w0rYCIimZ2FL5r07H2dq9MgAeCb+NhjShludtrV1d9DPKRfqODC8HRZEKY9Xy2n/FadTlPuuSlZSSGg2iaCeeGxPA43Te+HoG83mRpQTafLvSoBINfQd7CCT3R9vAj0LpVcELGJaNiqWSve/Q8g7nf2bGiozBwjb50s5teJpwWZI8lgVXGW7ACgyeR7cAT489M3KGnO7Tt2Y+AgkTzEj/Lm2Vm2sMDzKsuaTxfbofs+a4FeEFjan1STWJIMpwAv+hfx8EQ+P5N+17mzBPVWvc/3HJ4N6OxPQZO1ec/9k5kjJQMoHBcyK0OwIzZHGJ6fU+Q/suiwq0b1JpVDWBlCGLN9KUmo1tdLLMqivxSIkzUzPiQp02OxOy0DzO9MofkGgg1OeB57X5VY4Wpq8=
