travis:
  secure:
    BINSTAR_TOKEN: RP/5R3Rc7cbhoJ7ZBRaz7bonpwHVG+ZyijvZHhvLH5IJhtObgmUIRgmHf+0I/vVYoDNND2xquo3Svdkjyl2LA503RsvrIc9ZVluKwTVJmTA279sJe8mlBqUaGuwBRDq7Lha+CaItmjiELsdy7JmPaGLrIEoemL5BVVoD4LzrVHEnW5Ef1JSAF40AzuUMNNMQ0nQZLEmwlS7pmR5MFdt8Fo1GMOhb5xYkaVll4kyW5pyz0j/uxb8A7KOIceaO8MIrKrGGnlAfvyA6Z6meQ8elxpKFYRKKoHXc+b4/SdJASWbeAjR16wT9MD8qAb6+gf4xzA+RPY2gqoBFzTVIpFU/oGF5tXTLev2PYkYdkwxhsuxfwnGIlPRozql5pC1leewtdBfFfq3LsLJ8T4z74glWNR4aN/MkwU+B56kaktzXSSc2uwbyXdJkQtpa39ouzJ+tb8+uqpjSVBhYfUU3gI00o81OVXggtlouCiZYrnhkW9r8shZxiv7kk8nGgw2ozhlx/+AwVbucZvHav68mWrezxKGfccfWF8+MloG7xMKx0KmeEcRpflrF8zDO38zbDmAJs1oZlBZQiB+fjalwWqqa1DUAytnA4SexNqXuCkIL7br/1n38FDDhU7/X0/5SJGl6LFbcLyexDP6UbDxK726l8VsDiPVRqG3+lIuJlydDqzU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
